#ifndef CRITICAL_H
#define CRITICAL_H

#define CRITICAL_ERROR_COUNT_FAILURE 50

extern S32 CriticalErrorCount;

// ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
extern int CriticalErrorHandler(unsigned int deverr,
																unsigned int errcode,
																unsigned int *devhdr);

// ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
#define InstallCriticalErrorHandler() _harderr(CriticalErrorHandler)

#endif // CRITICAL_H
