// ──────────────────────────────────────────────────────────────────────────
#include <SYSTEM/ADELINE.H>
#include <SYSTEM/INITKEYB.H>

// ──────────────────────────────────────────────────────────────────────────
#include <SYSTEM/WINSYS.H>
#include <SYSTEM/KEYBWIN.H>

// ──────────────────────────────────────────────────────────────────────────
void InitKeyboard()
{
	// TODO: Implement
	// AsciiMutex = CreateMutex(NULL, FALSE, NULL);

	// if (!AsciiMutex)
	// {
	// 	exit(1);
	// }

	// OldKeybWindowProc = WindowProc;
	// WindowProc = KeybWindowProc;
}

// ──────────────────────────────────────────────────────────────────────────
void ClearKeyboard()
{
	// TODO: Implement
	// WindowProc = OldKeybWindowProc;
}
