//-------------------------------------------------------------------------
#include <SYSTEM/ADELINE.H>
#include <SYSTEM/INITIMER.H>

#include <SYSTEM/WINSYS.H>
#include <SYSTEM/TIMERWIN.H>

//-------------------------------------------------------------------------
void InitTimer()
{
	// TODO: Implement
	// OldTimerWindowProc = WindowProc;
	// WindowProc = TimerWindowProc;
}

//-------------------------------------------------------------------------
void ClearTimer()
{
	// TODO: Implement
	// WindowProc = OldTimerWindowProc;
}
